name: Build macOS App

on:
  push:
    branches:
      - main
  workflow_dispatch:  # 支持手动触发

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      # 1️⃣ 拉取仓库代码
      - uses: actions/checkout@v3

      # 2️⃣ 设置 Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3️⃣ 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # 4️⃣ 使用 PyInstaller 打包为 macOS App
      - name: Build .app
        run: |
          pyinstaller --onefile --windowed --name "SupportTool" get_pod_tool.py --icon icon.icns

      # 5️⃣ 压缩 .app 为 zip
      - name: Archive .app
        run: |
          mkdir -p dist_artifact
          cp -R dist/SupportTool.app dist_artifact/
          cd dist_artifact
          zip -r SupportTool-mac.zip SupportTool.app

      # 6️⃣ 上传 artifact（使用 v4）
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SupportTool-mac
          path: dist_artifact/SupportTool-mac.zip
